name: compile

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'
    - name: Install Erlang
      uses: erlef/setup-beam@v1
      with:
        # version is used for download URL (see https://github.com/gleam-lang/setup-erlang/blob/main/main.sh)
        # Available versions: see https://www.erlang-solutions.com/downloads/
        otp-version: '26.x'
    - name: Build abstools
      uses: eskatos/gradle-command-action@v1
      env:
        LANG: en_US.UTF-8
      with:
        arguments: build -x check -x test
