name: compile

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - uses: gleam-lang/setup-erlang@v1.1.2
      with:
        otp-version: '23.2'
    - name: Build with Gradle
      env:
        LANG: en_US.UTF-8
      run: ./gradlew build -x check
